# This workflow will install Python dependencies and run tests

name: python-unittest-ci

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Set up MOSEK license
      env:
        MOSEK_LICENSE_KEY: ${{ secrets.MOSEK_LICENSE_KEY }}
      run: |
        mkdir -p $HOME/mosek
        echo "$MOSEK_LICENSE_KEY" > $HOME/mosek/mosek.lic
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./test  -p 'test_*.py'
