# This workflow will install Python dependencies and run tests

name: test

on:
  push:
    branches: [ ]    # Run tests on pushes to any branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install mosek numba networkx numpy scipy sympy tqdm
    - name: Set up MOSEK license
      env:
         MOSEK_LICENSE_KEY: ${{ secrets.MOSEK_LICENSE_KEY }}
      run: |
         mkdir -p $HOME/mosek
         echo "$MOSEK_LICENSE_KEY" > $HOME/mosek/mosek.lic
    - name: Test with pytest
      run: |
         pytest -v
    - name: Clean up MOSEK license file
      run: |
         rm $HOME/mosek/mosek.lic
